## Package configuration
CONFIG = RELEASE

## List of C++ files that hold your implementation of parallel sort
## Files must have etension .cpp
SORT_CXX_FILES = sort.cpp
## List of C files that hold your implementation of parallel sort
## Files must have etension .c
SORT_CC_FILES = 

## Additional compiler flag to pass to C-compiled sources
CFLAGS = 
## Additional compiler flags to pass to C++-compiled sources
CXXFLAGS = -std=c++11 -Wall
## Additional linker flags
CXX_LDFLAGS = -lpthread -lrt

## Number of threads to compile
NB_THREADS = 4

## Task graph description
DRAKE_TASKGRAPH = merge-4.graphml
## Drake target paltform description
DRAKE_PLATFORM = platform-4.dat
## Drake schedule to use
DRAKE_SCHEDULE = schedule-4.xml ## Let lpt generate a schedule
